### ISSUE TITLE
Code to start activity missing

### ISSUE THREAD

**Issue by haseebpvt** [HashimJVZ/NSS-VAST#3]
[Check this line](https://github.com/HashimJVZ/NSS-VAST/blob/b8584da9060384dfe2922d8084a1f4dcac3143f3/app/src/main/java/com/vast/nss/MainActivity.java#L86)

`startActivity(intent);` line missing

**Comment by HashimJVZ** [comment]
LGTM, Issue Fixed, Added Line.

**Comment by HashimJVZ** [comment]
LGTM, Issue Fixed by adding line.
