### ISSUE TITLE
Firebase data unavailable

### ISSUE THREAD

**Issue by HashimJVZ** [HashimJVZ/NSS-VAST#4]
Data from the firebase is either not receiving or not displaying

**Comment by haseebpvt** [comment]
Provide more details. Like on which activity/fragment.

**Comment by HashimJVZ** [comment]
Event Fragment

**Comment by haseebpvt** [comment]
I'll check this

**Comment by HashimJVZ** [comment]
Fixed by changing rules in Database and remapping layout id
